---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/thenet84/concourse-tutorial.git
      branch: develop

  - name: my-timer
    type: time
    source:
      interval: 1m

jobs:
  - name: job-hello-world
    public: true
    serial: true
    plan:
      - get: resource-tutorial
      - get: my-timer
        trigger: true
      - task: my-first
        file: resource-tutorial/turorials/basic/task-hello-world/task_my_first.yml
      - task: hello-world
        file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml